### ISSUE TITLE
Feature/Blockquote

### ISSUE THREAD

**Issue by Snugug** [IBM-Watson/patterns#53]
Create Blockquote element and style

**Comment by una** [comment]
please link styling in here @britanyponvelle

**Comment by britanyponvelle** [comment]
![screen shot 2015-03-05 at 6 38 39 pm](https://cloud.githubusercontent.com/assets/9538528/6518031/eed0ead6-c366-11e4-9db9-18d6a4e1e8ce.png)

This is from the style tile. I had it in the base text size (1 em) with emphasized text
