### ISSUE TITLE
Feature/A

### ISSUE THREAD

**Issue by Snugug** [IBM-Watson/patterns#57]
Anchor Tag

**Comment by una** [comment]
base files set up and ready for styling for this along with other tags, should I do a PR or wait?

**Comment by Snugug** [comment]
Each feature should get its own PR and should come with styling. All of these are just stubs.

**Comment by una** [comment]
With all of the input types, there were PRs made without styling -- should I not continue that model?

**Comment by Snugug** [comment]
These won't be closed until they have styling. Do whatever you think will let us move faster.
