### ISSUE TITLE
Explore additional precedents

### ISSUE THREAD

**Issue by kathrynmcelroy** [IBM-Watson/patterns#91]
- [x] go through existing examples of style guides that are in the Release Blueprints
- [x] find additional if necessary

**Comment by Snugug** [comment]
Is this its own task or is this something you'll be doing in association with #92?

**Comment by kathrynmcelroy** [comment]
I guess it could be added to 92, I just have it separate in my to do list.

**Comment by Snugug** [comment]
If you think it's a separate task and not a sub-task of one of your other tasks, I can label it up, but if you think it's a sub-task, we can close it and add the items to the parent task

**Comment by kathrynmcelroy** [comment]
I'd like to keep it as separate. 92 is more about exploring/ideation, this is still about understanding/research.

**Comment by Snugug** [comment]
Done
