### ISSUE TITLE
Color palettes for user testing

### ISSUE THREAD

**Issue by bobbinrobyn** [IBM-Watson/patterns#94]
- [x] Digitize with hex values
- [x] Compare to IBM Design colors
- [x] Check accessibility for each color 
- [x] Determine 10 tints & shades for each color with numerical label (e.g. Green 10, Green 20, etc)

**Comment by bobbinrobyn** [comment]
You can see my progress here: http://pages.design.ibm.com/rlhammon/watson-color-palettes/master/palettes_rh.html

**Comment by bobbinrobyn** [comment]
http://pages.design.ibm.com/rlhammon/watson-color-palettes/master/palettes_rh.html

**Comment by bobbinrobyn** [comment]
These were the results from user testing:
With Watson designers – https://releaseblueprints.ibm.com/display/WDA/Testing+Final+Palettes
With non-Watson designers – https://releaseblueprints.ibm.com/display/WDA/Testing+Final+Palettes

**Comment by Snugug** [comment]
Can we move this in to our wiki here?
